version: '2.12.2'
services:

  simplelocalpathplanner:
    container_name: turtlebot3_simple_local_path_planner
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ROS_VERSION: noetic
    # command: ["bash", "-c", "source /catkin_ws/devel/setup.bash && roslaunch simple_local_path_planner turtlebot3_navigation.launch"] 
    user: root
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY                #GUI
      - NVIDIA_DRIVER_CAPABILITIES=all  #GUI
      - NVIDIA_VISIBLE_DEVICES=all      #GUI
      - TURTLEBOT3_MODEL=burger         #Turtlebot3 model
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'  #GUI
      - .:/catkin_ws/src/simple_local_path_planner:rw # Mount package for development. Will probably copy to docker image once finished.
      - ./.vscode:/catkin_ws/.vscode:rw     # Copy extension settings to support dev container

# Todo: Add container script to run unit tests